### ISSUE TITLE
Job Completion

### ISSUE THREAD

**Issue by fdm-jdnora** [lucas34/SwiftQueue#195]
How can I subscribe to a Job's callback?

i.e. I execute my Job in a View Model and I want to know the result of the job inside the View Model

**Comment by lucas34** [comment]
This is currently not supported since the job can be persisted and will be re-created at the app level. So your ViewModel will not be listening anymore.
If you want to update your view my flow was like this

View model -> Schedule Job -> Job execution -> Update database
View model -> listen for database update -> Update

**Comment by fdm-jdnora** [comment]
Thank you Lucas! I was also considering using notification observers. I will try your approach. Thanks again

**Comment by lucas34** [comment]
This may help https://github.com/lucas34/SwiftQueue/pull/218
