### ISSUE TITLE
How to use(activate) background tasks API  with swiftqueue?

### ISSUE THREAD

**Issue by tirthpatelflynn** [lucas34/SwiftQueue#293]
I have tried to use it like below 
`let manager = SwiftQueueManagerBuilder(creator: ImageUploadJobCreator())
                        .set(initInBackground: true)
                        .build()`
and whenever I try to go to background it throws this error.
`Can't end BackgroundTask: no background task exists with identifier 18 (0x12), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.`

**Comment by lucas34** [comment]
initInBackground is to asynchronously load all the jobs from the storage. It can be costly and this method will prevent from impacting your app startup time. 

It seems you are using Both initInBackground and periodic(executor = .background).


This is not possible since all task must be registered before  the end of applicationDidFinishLaunching

https://github.com/lucas34/SwiftQueue/blob/87599452a5c92abbf40d07f33dc096ca9009aa69/Sources/ios/SwiftQueueManager%2BBackgroundTask.swift#L32

**Comment by lucas34** [comment]
I'll try to improve the documentation once the Background API is stable.
