### ISSUE TITLE
SwiftQueue deserialization issues

### ISSUE THREAD

**Issue by momentsdesigns** [lucas34/SwiftQueue#334]
Hi there!

I'm using SwiftQueue to process a "Sync" job, and have been seeing crashes that I can't reproduce myself.

Specifically, it appears that on launch, we add a new sync job, which initializes the queue and calls `loadSerializedTasks`. SwiftQueue then attempts to call `create` on my `SyncJobCreator`:

```swift
let syncQueueManager = SwiftQueueManagerBuilder(creator: SyncJobCreator()).build()
```

```swift
class SyncJobCreator: JobCreator {
    func create(type: String, params: [String: Any]?) -> Job {
        if type != SyncJob.type {
            fatalError("SyncJobCreator error")
        }
        
        // Optional
        let lastUpdatedTimestamp = params?["lastUpdatedTime"] as? Int64
        
        return SyncJob(lastUpdatedTimestamp: lastUpdatedTimestamp)
    }
}
```

Most of the time, the job gets successfully created. **However, occasionally we seem to be hitting the `fatalError` around the job type not matching.**

This particular `Job` is not even told to persist (via `.persist(required: false)`, so I'm unsure what it's even trying to deserialize (again, I wish I could reproduce this issue myself). And even if it _was_ told to persist, I would expect the type and parameters to correctly deserialize later, right?

Here's where we actually add the job:

```swift
func queueSync(lastUpdated: Int64? = nil) {
    JobBuilder(type: SyncJob.type)
        .parallel(queueName: SyncJob.type)
        
        .internet(atLeast: .cellular)
    
        .with(params: [
            "lastUpdatedTime" : lastUpdated ?? APIManager.shared.lastUpdated
        ]).retry(limit: .limited(1))
        
        .deadline(date: Date(timeIntervalSinceNow: 60))
      
        .persist(required: false)
    
        .schedule(manager: syncQueueManager)
}
```

It's worth noting I do have _another_ queueManager elsewhere in the project (`uploadQueueManager`, `UploadPhotoJobCreator`, and `UploadPhotoJob`), but they don't interact at all.

Finally, I've attached a crash log that includes the symbolicated backtrace that I'm describing here. Any help would be incredibly helpful – thank you!

[crashlog.txt](https://github.com/lucas34/SwiftQueue/files/4708183/crashlog.txt)

**Comment by lucas34** [comment]
From what I understand the issue is when having 2 queue Manager. By default, the queue persist the jobs inside the UserDefaults under the key "SwiftQueueInfo". 

When you are creating the 2nd SwiftQueueManager, it will use the default UserDefaultPersister and will try to read from this memory Space. it will indeed crash since this queue doesn't support persistance.

To solve your issue you should set a custom persister. You can use 

```swift
.set(persister: UserDefaultsPersister(key: "SyncQueue"))
```

Or if this manager doesn't support persistance at all you can use `NoSerializer` from the Test class.

**Comment by momentsdesigns** [comment]
Hi Lucas – thanks so much for the prompt and detailed response!

It seems like I have three options here. Would you mind telling me if these three options are correct/interchangeable, and if so, which you'd recommend (i.e. which is the "best-practice" route)?

1. Set each `SwiftQueueManager`'s persister to a custom `UserDefaultsPersister` with a unique key (i.e. `SyncQueue` and `UploadJobQueue`. This way no queue manager is using the `SwiftQueueInfo` key.

2. Copy the `NoSerializer` class from the tests, and set the `syncQueueManager`'s persister to an instance of that, while keeping everything else the same.

3. Use _one_ queue manager for _both_ tasks, returning a different `Job` based on the `type` parameter. Not sure if this is compatible with one task that's persistent and another that's not.

What do you think are the best options? Thanks!

**Comment by lucas34** [comment]
By design, the library should only have 1 QueueManager. Not sure what other edge case you may face by having multiple QueueManager. So I would say solution 3 should be the best. 

Either 1 or 2 may solve the issue. But if you create another SwiftQueueManager in the future with default params, You will face this issue again.

**Comment by momentsdesigns** [comment]
Great, that makes sense. Thanks for clearing this up for me.
