### ISSUE TITLE
Possibility to have a pre-run hook

### ISSUE THREAD

**Issue by foxware00** [lucas34/SwiftQueue#373]
I'll explain my scenario.
I'm sending messages in a chat app. I want to insert a local copy of the message, then in-order send off all the messages, showing a loading indicator for messages unsent. 
For this task, I'm using the `.group` to make sure they all run in parallel.

Currently, on poor networks, jobs aren't executed until the previous job was successfully run as i'd expect. But I need to manage a pre-job state separately and think it might be a clean optional addition to scheduling a job.

My question is does having the option of a callback (`.onJobAdded()` or similar) when the job is added make sense in the libary or should I manage this separately.

**Comment by arthurdapaz** [comment]
We already have a **JobListener** protocol, with `func onBeforeRun(job: JobInfo)`

If you really want some **.onJobAdded()** it makes more sense for you to, right after creating your job, you run your own desired code block. Which is clearly dangerous, since you're not sure if all of your job's constraints are being satisfied at the moment. That's why **JobListener** is the to-go way for your request.
